[package]
name = "floem_vger"
version = "0.1.0"
edition = "2021"
license.workspace = true

[dependencies]
resvg = "0.33.0"
wgpu = "0.18.0"
raw-window-handle = "0.5.1"
futures = "0.3.26"
anyhow = "1.0.69"
peniko = { git = "https://github.com/linebender/peniko", rev = "cafdac9a211a0fb2fec5656bd663d1ac770bcc81" }
swash = "0.1.8"
vger = { git = "https://github.com/lapce/vger-rs", rev = "ed10537c72a732a03f782225a39da80e6f9acbbe" }
# vger = { path = "../../vger-rs" }
image = { version = "0.24", features = ["jpeg", "png"] }
floem_renderer = { path = "../renderer" }
